name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
      GOOGLE_PASS: ${{ secrets.GOOGLE_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug DATABASE_URL
        run: echo "DATABASE_URL is $DATABASE_URL"
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install dependencies
        run: npm install

      - name: Debug DATABASE_URL
        run: echo "DATABASE_URL starts with ${DATABASE_URL}..."

      - name: Run lint
        run: npm run lint

      - name: Build project
        run: npm run build
